// <auto-generated />
// https://docs.microsoft.com/dotnet/core/compatibility/sdk/6.0/implicit-namespaces
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;