// <auto-generated>
// </auto-generated>

[module: System.Runtime.CompilerServices.SkipLocalsInit]

#if !NET5_0_OR_GREATER || NETSTANDARD2_1 || NETSTANDARD2_0
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(
        AttributeTargets.Module
        | AttributeTargets.Class
        | AttributeTargets.Struct
        | AttributeTargets.Constructor
        | AttributeTargets.Method
        | AttributeTargets.Property
        | AttributeTargets.Event,
        Inherited = false)]
    sealed class SkipLocalsInitAttribute : Attribute
    {
        public SkipLocalsInitAttribute()
        {
        }
    }
}
#endif