version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: Microsoft.SourceLink.GitHub
      - dependency-name: StyleCop.Analyzers