version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    ignore:
      - dependency-name: Microsoft.SourceLink.GitHub
      - dependency-name: StyleCop.Analyzers

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
