version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: StyleCop.Analyzers
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily