name: Build(YAML)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML code
        run: yamllint .