name: Build(Markdown)

on:
  pull_request:
    paths:
      - '**/*.md'
      - .markdownlint.yml
      - .github/workflows/build-markdown.yml

permissions:
  contents: read

jobs:
  main:
    uses: finphie/Actions/workflows/build-markdown.yml@main
