name: Build(Python)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.py'
      - .github/workflows/build-python.yml

jobs:
  check:
    name: Check
    if: github.event.repository.name != 'dotfiles'
    runs-on: ubuntu-latest

    outputs:
      lint: ${{ steps.check.outputs.lint }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Check file
        id: check
        shell: pwsh
        run: |
          $files = Get-ChildItem . -Recurse -Name -Include '*.py'
          Write-Output $files
          Write-Output "::set-output name=lint::$($files.Length -gt 0)"

  lint:
    name: Lint
    needs: check
    if: needs.check.outputs.lint == 'True'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install flake8
        run: pip install flake8

      - name: Install Pyright
        run: sudo npm install -g pyright

      - name: Lint Python code
        run: |
          flake8
          pyright