name: Build(Python)

on:
  pull_request:
    paths:
      - '**/*.py'
      - .github/workflows/build-python.yml

permissions: {}

jobs:
  main:
    uses: finphie/Actions/.github/workflows/build-python.yml@main
