name: Build(.NET)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/Directory.Build.props'
      - '**/Directory.Build.targets'
      - '**/.editorconfig'
      - .github/workflows/build-dotnet.yml

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  dotnet-version: '6.0'

jobs:
  check:
    name: Check
    if: github.event.repository.name != 'dotfiles'
    runs-on: ubuntu-latest

    outputs:
      test: ${{ steps.check.outputs.test }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check file
        id: check
        shell: pwsh
        run: Write-Output "::set-output name=test::$(Test-Path *.sln)"

  test:
    name: Test
    needs: check
    if: needs.check.outputs.test == 'True'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}
          include-prerelease: true

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        if: matrix.os != 'macOS-latest'
        with:
          dotnet-version: 5.x

      - name: .NET Build
        run: dotnet build --configuration Release -warnAsError

      - name: .NET Test
        run: dotnet test --configuration Release --no-build