name: Build(Python)

on:
  pull_request:
    paths:
      - '**/*.py'
      - .github/workflows/build-python.yml

permissions:
  contents: read

jobs:
  main:
    uses: finphie/Actions/workflows/build-python.yml@main
