name: Build(.NET)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/Directory.Build.props'
      - '**/.editorconfig'
      - .github/workflows/build-dotnet.yml

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  dotnet-version: 6.0.100-preview.2.21155.3

jobs:
  check:
    name: Check
    if: github.event.repository.name != 'dotfiles'
    runs-on: ubuntu-latest

    outputs:
      test: ${{ steps.check.outputs.test }}
      lint: ${{ steps.check.outputs.lint }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check file
        id: check
        shell: pwsh
        run: |
          Write-Output "::set-output name=test::$(Test-Path Tests/*.Tests)"
          Write-Output "::set-output name=lint::$(Test-Path *.sln)"

  test:
    name: Test
    needs: check
    if: needs.check.outputs.test == 'True'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      # Windowsでエラーになる問題の回避
      # https://github.com/actions/setup-dotnet/issues/155
      - name: Clean
        if: matrix.os == 'windows-latest'
        run: |
          dotnet clean
          dotnet nuget locals all --clear

      - name: .NET Build
        run: dotnet build --configuration Release

      - name: .NET Test
        run: dotnet test --configuration Release --no-build

  lint:
    name: Lint
    needs: check
    if: needs.check.outputs.lint == 'True'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: .NET restore
        run: dotnet restore

      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

      - name: Lint .NET code
        run: dotnet format --check --fix-whitespace --fix-style info --fix-analyzers info --verbosity diagnostic