name: Build(.NET)

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.tt'
      - '**/*.xaml'
      - '**/*.razor'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.props'
      - '**/*.targets'
      - '**/.editorconfig'
      - '**/.globalconfig'
      - .github/workflows/build-dotnet.yml

permissions:
  contents: read

jobs:
  main:
    uses: finphie/Actions/workflows/build-dotnet.yml@main
