name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.json

permissions: {}

jobs:
  check:
    name: Check
    uses: finphie/Actions/.github/workflows/get-version.yml@main

  main:
    name: Main
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release Drafter
        uses: toolmantim/release-drafter@v5
        permissions:
          contents: write
        with:
          publish: true
          prerelease: false
          name: Version ${{ needs.check.outputs.version }}
          tag: v${{ needs.check.outputs.version }}
          version: ${{ needs.check.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
