name: Update repository.json

on:
  pull_request:
    paths:
      - '**/*.csproj'

permissions:
  contents: write

jobs:
  main:
    name: Main
    uses: finphie/Actions/.github/workflows/update-repository-json.yml@main
